# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave-nightly.nix (removeAttrs args [ "callPackage" ])
  (
    if stdenv.isAarch64 then
      {
        pname = "brave-browser-nightly";
        version = "1.75.105";
        url = "https://github.com/brave/brave-browser/releases/download/v1.75.105/brave-browser-nightly_1.75.105_arm64.deb";
        hash = "sha256-Vf+FCuFGqXXQyXqkjEqtN2CrWLzt8p6TOv6Gs3YUG20=";
        platform = "aarch64-linux";
      }
    else if stdenv.isx86_64 then
      {
        pname = "brave-browser-nightly";
        version = "1.75.105";
        url = "https://github.com/brave/brave-browser/releases/download/v1.75.105/brave-browser-nightly_1.75.105_amd64.deb";
        hash = "sha256-mSxZ4XuX77Rm7u7ATCMXLtmZRaiScEYnzDR+R1Dpluk=";
        platform = "x86_64-linux";
      }
    else
      throw "Unsupported platform."
  )
