# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave-nightly.nix (removeAttrs args [ "callPackage" ]) (
  if stdenv.isAarch64 then
    {
      pname = "brave-browser-nightly";
      version = "1.70.11";
      url = "https://github.com/brave/brave-browser/releases/download/v1.70.11/brave-browser-nightly_1.70.11_arm64.deb";
      hash = "sha256-4kE+aLLxBo85mRdnJTikpTc+pLxE4k3E07RtFv7AcwI=";
      platform = "aarch64-linux";
    }
  else if stdenv.isx86_64 then
    {
      pname = "brave-browser-nightly";
      version = "1.70.11";
      url = "https://github.com/brave/brave-browser/releases/download/v1.70.11/brave-browser-nightly_1.70.11_amd64.deb";
      hash = "sha256-a07Ryiu0RLaKwfGhetH/9ASVnWxEI5GPvhRB+D7b8HA=";
      platform = "x86_64-linux";
    }
  else
    throw "Unsupported platform."
)
