# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ])
  (
    if stdenv.isAarch64 then
      {
        pname = "brave";
        version = "1.65.123";
        url = "https://github.com/brave/brave-browser/releases/download/v1.65.123/brave-browser_1.65.123_arm64.deb";
        hash = "sha256-4GNQ/p4KmDykwgoEdwzOHInA5QxGP4GDLuXOSdKyzzU=";
        platform = "aarch64-linux";
      }
    else if stdenv.isx86_64 then
      {
        pname = "brave";
        version = "1.65.123";
        url = "https://github.com/brave/brave-browser/releases/download/v1.65.123/brave-browser_1.65.123_amd64.deb";
        hash = "sha256-Jaru2milLNLdlEE1CAQD8RH1QWgKQLJNsommIMzM94s=";
        platform = "x86_64-linux";
      }
    else
      throw "Unsupported platform."
  )
