name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        hostname:
          - edge
          - pangolin
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Cache in Flakehub Cache
        uses: DeterminateSystems/flakehub-cache-action@main        
      
      - name: Remove unnecessary files
        run: |
          echo "=== Before ==="
          df -h
          sudo rm -rf /usr/share /usr/local /opt
          echo "=== After ==="
          df -h  

      - name: Build It
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L     

