name: Update Flake Daily

on:
  schedule:
    # Runs at 5am UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-flake:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          commit-message: 'flake: update inputs'
          pr-title: 'flake: update inputs'
          pr-labels: automated

      - uses: mdarocha/comment-flake-lock-changelog@main
        if: ${{ steps.update-flake-lock.outputs.pull-request-number != 0 }}
        with:
          pull-request-number: ${{ steps.update-flake-lock.outputs.pull-request-number }}
          
          

